"""Add authorization_id and policy_version to AuditEvent

Revision ID: cd504803243b
Revises: fd9297459dd0
Create Date: 2026-09-01 23:17:00.373637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd504803243b'
down_revision: Union[str, None] = 'fd9297459dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('authorization_id', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('policy_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'policy_version')
    op.drop_column('audit_events', 'authorization_id')
    # ### end Alembic commands ###
