"""Add lineage fields to approval_requests

Revision ID: d270af37167d
Revises: e0f6638b250c
Create Date: 2026-09-09 12:08:46.881829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd270af37167d'
down_revision: Union[str, None] = 'e0f6638b250c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('parent_request_id', sa.String(), nullable=True))
    op.add_column('approval_requests', sa.Column('parent_authorization_id', sa.String(), nullable=True))
    op.add_column('approval_requests', sa.Column('decision_attempt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'decision_attempt')
    op.drop_column('approval_requests', 'parent_authorization_id')
    op.drop_column('approval_requests', 'parent_request_id')
    # ### end Alembic commands ###
