"""Add PolicyVersion and update Float to Numeric

Revision ID: fd9297459dd0
Revises: ae057ba55dfd
Create Date: 2026-09-01 23:15:55.448356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9297459dd0'
down_revision: Union[str, None] = 'ae057ba55dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rego_content', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('agent_permissions', 'max_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('agent_permissions', 'requires_approval_above',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.add_column('approval_requests', sa.Column('operator_id', sa.String(), nullable=True))
    op.alter_column('approval_requests', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.add_column('audit_events', sa.Column('previous_hash', sa.String(), nullable=True))
    op.add_column('audit_events', sa.Column('event_hash', sa.String(), nullable=True))
    op.alter_column('audit_events', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('audit_events', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('budgets', 'limit_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('policies', 'rego_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('rego_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('budgets', 'limit_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('audit_events', 'latency_ms',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('audit_events', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('audit_events', 'event_hash')
    op.drop_column('audit_events', 'previous_hash')
    op.alter_column('approval_requests', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('approval_requests', 'operator_id')
    op.alter_column('agent_permissions', 'requires_approval_above',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('agent_permissions', 'max_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_table('policy_versions')
    # ### end Alembic commands ###
